services:
  gemfactory:
    image: tempizhere/gemfactory:latest
    container_name: gemfactory
    pull_policy: always
    restart: unless-stopped
    environment:
      # Основные настройки
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - WHITELIST_DIR=data
      - TZ=Asia/Seoul

      # Настройки кэша
      - CACHE_DURATION=8h

      # Настройки запросов
      - MAX_RETRIES=3
      - REQUEST_DELAY=10s
      - MAX_CONCURRENT_REQUESTS=5

      # Retry настройки
      - RETRY_MAX_ATTEMPTS=3
      - RETRY_INITIAL_DELAY=1s
      - RETRY_MAX_DELAY=30s
      - RETRY_BACKOFF_MULTIPLIER=2.0

      # Продвинутые настройки
      - METRICS_ENABLED=false
      - HEALTH_CHECK_INTERVAL=30s
      - GRACEFUL_SHUTDOWN_TIMEOUT=30s

      # Настройки производительности
      - HTTP_MAX_IDLE_CONNS=100
      - HTTP_MAX_IDLE_CONNS_PER_HOST=10
      - HTTP_IDLE_CONN_TIMEOUT=90s
      - HTTP_TLS_HANDSHAKE_TIMEOUT=10s
      - HTTP_RESPONSE_HEADER_TIMEOUT=30s
      - HTTP_DISABLE_KEEP_ALIVES=false

      # Логирование
      - LOG_LEVEL=info
    volumes:
      - whitelist_data:/app/data
    healthcheck:
      test: [ "CMD", "pgrep", "gemfactory" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
volumes:
  whitelist_data:
    name: whitelist_data
