services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - whitelist_data:/app/internal/features/releasesbot/data
    restart: unless-stopped

volumes:
  whitelist_data:
    name: whitelist_data