-- Migration: Add artists to the database
-- Description: Adds female and male K-pop artists to the artists table (only if they don't exist)

-- Insert female artists (only if they don't exist)
INSERT INTO artists (name, gender, is_active) VALUES
('ablume', 'female', true),
('artms', 'female', true),
('atheart', 'female', true),
('baby dont cry', 'female', true),
('babymonster', 'female', true),
('badvillain', 'female', true),
('bewave', 'female', true),
('bibi', 'female', true),
('billlie', 'female', true),
('burvey', 'female', true),
('candy shop', 'female', true),
('chuu', 'female', true),
('class:y', 'female', true),
('crazangel', 'female', true),
('dreamnote', 'female', true),
('fifty fifty', 'female', true),
('fromis_9', 'female', true),
('gyubin', 'female', true),
('h1-key', 'female', true),
('hanhee', 'female', true),
('hearts2hearts', 'female', true),
('hitgs', 'female', true),
('hyuna', 'female', true),
('i-dle', 'female', true),
('ichillin''', 'female', true),
('ifeye', 'female', true),
('illit', 'female', true),
('irene', 'female', true),
('irene & seulgi', 'female', true),
('iu', 'female', true),
('izna', 'female', true),
('jennie', 'female', true),
('jeon somi', 'female', true),
('kandis', 'female', true),
('kiiikiii', 'female', true),
('kiiras', 'female', true),
('kiss of life', 'female', true),
('kwon eunbi', 'female', true),
('lightsum', 'female', true),
('lisa', 'female', true),
('meovv', 'female', true),
('meowmiro', 'female', true),
('minnie', 'female', true),
('misamo', 'female', true),
('miyeon', 'female', true),
('moon byul', 'female', true),
('mrch', 'female', true),
('mλdein', 'female', true),
('odd youth', 'female', true),
('oh my girl', 'female', true),
('olivia marsh', 'female', true),
('primrose', 'female', true),
('purple kiss', 'female', true),
('rescence', 'female', true),
('rolling quartz', 'female', true),
('rosé', 'female', true),
('say my name', 'female', true),
('seulgi', 'female', true),
('solar', 'female', true),
('soorin', 'female', true),
('spia', 'female', true),
('summer cake', 'female', true),
('taeyeon', 'female', true),
('triples', 'female', true),
('uau', 'female', true),
('udtt', 'female', true),
('unis', 'female', true),
('viviz', 'female', true),
('vvs', 'female', true),
('vvup', 'female', true),
('wendy', 'female', true),
('wjsn', 'female', true),
('wooah', 'female', true),
('xg', 'female', true),
('yeji', 'female', true),
('yena', 'female', true),
('you dayeon', 'female', true),
('young posse', 'female', true),
('yuju', 'female', true),
('yuqi', 'female', true),
('yves', 'female', true)
ON CONFLICT (name) DO NOTHING;

-- Insert male artists (only if they don't exist)
INSERT INTO artists (name, gender, is_active) VALUES
('&team', 'male', true),
('82major', 'male', true),
('8turn', 'male', true),
('ab6ix', 'male', true),
('all(h)ours', 'male', true),
('allday project', 'male', true),
('ampers&one', 'male', true),
('arrc', 'male', true),
('axmxp', 'male', true),
('bambam', 'male', true),
('band lucy', 'male', true),
('boynextdoor', 'male', true),
('chen', 'male', true),
('cortis', 'male', true),
('forestella', 'male', true),
('idid', 'male', true),
('kai', 'male', true),
('kard', 'male', true),
('kave', 'male', true),
('key', 'male', true),
('kickflip', 'male', true),
('nct dream', 'male', true),
('nexz', 'male', true),
('nouera', 'male', true),
('p1harmony', 'male', true),
('riize', 'male', true),
('taemin', 'male', true),
('taeyong', 'male', true),
('ten', 'male', true),
('wayv', 'male', true),
('whib', 'male', true),
('xdinary heroes', 'male', true),
('xikers', 'male', true),
('zerobaseone', 'male', true)
ON CONFLICT (name) DO NOTHING;

-- Update sequence to avoid conflicts
SELECT setval('artists_artist_id_seq', (SELECT MAX(artist_id) FROM artists));