services:
  gemfactory:
    image: tempizhere/gemfactory:latest
    container_name: gemfactory
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Обязательные настройки
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - TZ=${TZ}

      # Spotify настройки
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - PLAYLIST_URL=${PLAYLIST_URL}
      - PLAYLIST_UPDATE_HOURS=${PLAYLIST_UPDATE_HOURS}

      # Настройки кэша
      - CACHE_DURATION=${CACHE_DURATION}

      # Настройки запросов
      - REQUEST_DELAY=${REQUEST_DELAY}
      - MAX_RETRIES=${MAX_RETRIES}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS}

      # Настройки rate limiting
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW}

      # Логирование
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_OUTPUT=${LOG_OUTPUT:-both}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-logs/gemfactory.log}
      - LOG_MAX_SIZE=${LOG_MAX_SIZE:-100}
      - LOG_MAX_BACKUPS=${LOG_MAX_BACKUPS:-3}
      - LOG_MAX_AGE=${LOG_MAX_AGE:-28}

      # Настройки health check
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED}
      - HEALTH_CHECK_PORT=${HEALTH_CHECK_PORT}

      # Дополнительные настройки
      - METRICS_ENABLED=${METRICS_ENABLED}
    volumes:
      - app_data:/app/data
      - /var/log/gemfactory:/app/logs
    healthcheck:
      test: [ "CMD", "pgrep", "gemfactory" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
volumes:
  app_data:
    name: app_data
