server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Конфигурация для gemfactory логов
  - job_name: gemfactory
    static_configs:
      - targets:
          - localhost
        labels:
          job: gemfactory
          service: telegram_bot
          environment: local
          __path__: /var/log/gemfactory/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: ts
            message: msg
            caller: caller
            user_id: user_id
            username: username
            command: command
            duration: duration
            error: error
            track_id: track_id
            track_title: track_title
            track_artist: track_artist
            play_count: play_count
            service: service
            component: component
            handler: handler
            operation: operation
            result: result
            error_type: error_type
            request_id: request_id
            bot_username: bot_username
            female_artists: female_artists
            male_artists: male_artists
            total_artists: total_artists
            playlist_url: playlist_url
            tracks_count: tracks_count
            playlist_id: playlist_id
            total_tracks: total_tracks
            link_count: link_count
            month: month
            release_count: release_count
            port: port
            chat_id: chat_id
            update_id: update_id
            user: user
            count: count
            isFemale: isFemale
            time_until_next: time_until_next
            data: data
            requests: requests
            window: window
            current_month: current_month
            months: months
            total_releases: total_releases
            worker_id: worker_id
            stacktrace: stacktrace
      - labels:
          level:
          command:
          service:
          component:
          handler:
          operation:
          result:
          error_type:
          bot_username:
          female_artists:
          male_artists:
          total_artists:
          tracks_count:
          playlist_id:
          total_tracks:
          link_count:
          month:
          release_count:
          port:
          chat_id:
          update_id:
          user:
          count:
          isFemale:
          time_until_next:
          data:
          requests:
          window:
          current_month:
          months:
          total_releases:
          worker_id:
